server {
    listen 80;

    server_name activityfriend.com.tr www.activityfriend.com.tr;
    return 301 https://activityfriend.com.tr/$request_uri;
}

server {
    listen 443 ssl http2;

    server_name activityfriend.com.tr www.activityfriend.com.tr;

    include /etc/nginx/mime.types;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/css
    text/javascript
    text/xml
    text/plain
    application/javascript
    application/x-javascript
    application/json;

    gzip_disable "MSIE [1-6]\.";

    root /cdn;
    location / {
      try_files $uri $uri/ /index.html;
    }
}